# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: d11bf6b4b89385e4a620cc0b68d8e12fd093bf9742107ecc8aa97d9b785d7bafcfbc7695ac8d0738e2850539796444916e5bf214a246506182729b133c50fcb9

test:
  secret_key_base: c10d019ba266170fffd6fdc06a542d3f959b75fd0c3a8265345ea151955feff9bac09d999848e438652d4b660b434dcc116397939f5236f70a24fe7fd52d9188

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
